### ISSUE TITLE
bug: recording stopped

### ISSUE THREAD

**Issue by maximee-leroyy** [srcdslab/sm-plugin-AutoRecorder#5]
Recording stops if one of the following events occur:
- sourcetv moved to a team by an admin
- sourcetv gets kicked

We should find a way to either avoid these situations or enable back recording

- https://github.com/srcdslab/sm-plugin-BossHUD/issues/2#issuecomment-2137852489

**Comment by Rushaway** [comment]
Should we make a timer to check every 5 or 10s if the sourcetv is in team none/spec and if the record is stoped and conditions are ok to record, then start recording again ? 
For moving/kick sourcetv we cant prevent that I guess, it's up to plugins to dont allow to target sourcetv

**Comment by maximee-leroyy** [comment]
yes i think simply checking and fixing sourcetv with a timer should be ok (control this behavior with a cvar and disabled by default)
